image: alpine

build:
  image: lnl7/nix
  before_script:
    - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
    - nix-channel --update
    - nix-env -i curl
  script:
    - nix-build

pages:
  before_script:
    - apk --update add tar xz
  script:
    - mkdir -p public/
    - tar cJf public/$CI_COMMIT_REF_NAME.tar.xz --owner=0 --group=0 --mtime="1970-01-01 00:00:00 UTC" --transform="s|^\.|marsam-$CI_COMMIT_SHA|" ./pkgs/ ./default.nix
    - echo $CI_COMMIT_SHA > public/git-revision
  artifacts:
    paths:
      - public
  only:
    - master
